# Generated by Django 5.0 on 2024-08-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
