# Generated by Django 5.0 on 2024-08-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='Organizations'),
        ),
    ]
