# Generated by Django 5.0 on 2024-08-17 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_type', models.CharField(max_length=2555, verbose_name='firma turi')),
                ('mfo', models.CharField(blank=True, max_length=50, null=True, verbose_name='mfo')),
                ('oked', models.CharField(blank=True, max_length=50, null=True, verbose_name='oked')),
                ('inn', models.CharField(max_length=20, verbose_name='inn')),
                ('statute', models.ImageField(upload_to='ustav/', verbose_name='ustav')),
                ('guvohnoma', models.ImageField(upload_to='guvohnoma/')),
                ('director_passport', models.ImageField(upload_to='director_passport/', verbose_name='direktor pasport')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.organization')),
                ('tariff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.tariff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
