# Generated by Django 5.0 on 2024-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tariff_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='director_passport',
            field=models.FileField(upload_to='director_passport/', verbose_name='direktor pasport'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guvohnoma',
            field=models.FileField(upload_to='guvohnoma/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='statute',
            field=models.FileField(upload_to='ustav/', verbose_name='ustav'),
        ),
    ]
