# Generated by Django 5.0 on 2024-08-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_contract_director_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='telegram_group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
