# Generated by Django 5.0 on 2024-08-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='accounts.organization'),
            preserve_default=False,
        ),
    ]
