# Generated by Django 4.2.7 on 2023-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_volume_xajm_product_volume_xajm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume_xajm_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
