# Generated by Django 5.0 on 2024-08-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
