# Generated by Django 5.0 on 2024-08-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_minimum_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_price',
            field=models.BooleanField(default=False),
        ),
    ]
