# Generated by Django 4.2.7 on 2023-12-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_additional_info_key_ru_additional_info_key_uz_and_more'),
        ('order', '0003_orderinfo_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='size',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsize'),
        ),
    ]
