# Generated by Django 4.2.7 on 2023-12-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_additional_info_key_ru_additional_info_key_uz_and_more'),
        ('order', '0004_remove_orderinfo_color_remove_orderinfo_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_info_size', to='products.productsize'),
        ),
    ]
